version : 0.2

phases:
   pre_build:
    commands:
    - echo In the pre_build phase...   
  build :    
   commands:
     - echo entered the build phase...
     - mvn install
   post_build:
    commands:
     - echo Build complete successfully
   artifacts:
    files: 
     - target/authorization-service.jar
    discard-paths: yes         
